---
version: '2'

services:
  zcashd:
    image: gcr.io/zcash-web/zcashd:latest
    volumes:
      - $ZCASHD_DATADIR:/srv/zcashd/.zcash
      - $ZCASHD_PARMDIR:/srv/zcashd/.zcash-params
    environment:
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
      - ZCASHD_NETWORK=$ZCASHD_NETWORK
      - ZCASHD_ALLOWIP=$ZCASHD_ALLOWIP
    mem_limit: 4G
    ports:
      - "28332:28332"
      - "18232:18232"
  zcashd_exporter:
    build: .
    environment:
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
    command:
      - --rpc.host=zcashd
      - --rpc.port=18232
      - --rpc.user=$ZCASHD_RPCUSER
      - --rpc.password=$ZCASHD_RPCPASSWORD
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:6.4.3
    ports:
      - "3000:3000"
    environment:
      - GF_ADMIN_USER=$GF_ADMIN_USER
      - GF_ADMIN_PASSWORD=$GF_ADMIN_PASSWORD
  prometheus:
    image: prom/prometheus:v2.13.1
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/config.yml:/etc/prometheus/prometheus.yml

